/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for toad
*/

/*
    Board identifier
*/
#define BOARD_toad
#define BOARD_NAME                     "toad"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   26000000U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F405xx

/*
    IO pins assignments.
*/

#define GPIOA_GPS_PPS                  0U
#define GPIOA_PR_GPIO                  1U
#define GPIOA_PR_NSS                   2U
#define GPIOA_SR_NSS                   3U
#define GPIOA_GATE                     4U
#define GPIOA_SPI1_SCK                 5U
#define GPIOA_SPI1_MISO                6U
#define GPIOA_SPI1_MOSI                7U
#define GPIOA_GPS_GD                   8U
#define GPIOA_GPS_ERR                  9U
#define GPIOA_PR_GD                    10U
#define GPIOA_PR_ERR                   11U
#define GPIOA_SR_GD                    12U
#define GPIOA_SWDIO                    13U
#define GPIOA_SWCLK                    14U
#define GPIOA_SR_ERR                   15U

#define GPIOB_PIN0                     0U
#define GPIOB_B_TEMP                   1U
#define GPIOB_CHG_EN                   2U
#define GPIOB_CHG_GOOD                 3U
#define GPIOB_POWER_GOOD               4U
#define GPIOB_GPS_RST                  5U
#define GPIOB_UART_TX                  6U
#define GPIOB_UART_RX                  7U
#define GPIOB_I2C_SCL                  8U
#define GPIOB_I2C_SDA                  9U
#define GPIOB_SPI2_SCK                 10U
#define GPIOB_PR_NIRQ                  11U
#define GPIOB_PIN12                    12U
#define GPIOB_OTG_VBUS                 13U
#define GPIOB_OTG_DM                   14U
#define GPIOB_OTG_DP                   15U

#define GPIOC_SR_SW                    0U
#define GPIOC_PR_SW                    1U
#define GPIOC_SPI2_MISO                2U
#define GPIOC_SPI2_MOSI                3U
#define GPIOC_I_CHG_MON                4U
#define GPIOC_V_BAT_MON                5U
#define GPIOC_SYS_GD                   6U
#define GPIOC_SYS_ERR                  7U
#define GPIOC_SDIO_DO                  8U
#define GPIOC_SDIO_D1                  9U
#define GPIOC_SDIO_D2                  10U
#define GPIOC_SDIO_D3                  11U
#define GPIOC_SDIO_CK                  12U
#define GPIOC_PR_SDN                   13U
#define GPIOC_SR_SDN                   14U
#define GPIOC_SR_NIRQ                  15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_SDIO_CMD                 2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOE_PIN0                     0U
#define GPIOE_PIN1                     1U
#define GPIOE_PIN2                     2U
#define GPIOE_PIN3                     3U
#define GPIOE_PIN4                     4U
#define GPIOE_PIN5                     5U
#define GPIOE_PIN6                     6U
#define GPIOE_PIN7                     7U
#define GPIOE_PIN8                     8U
#define GPIOE_PIN9                     9U
#define GPIOE_PIN10                    10U
#define GPIOE_PIN11                    11U
#define GPIOE_PIN12                    12U
#define GPIOE_PIN13                    13U
#define GPIOE_PIN14                    14U
#define GPIOE_PIN15                    15U

#define GPIOF_PIN0                     0U
#define GPIOF_PIN1                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_PIN6                     6U
#define GPIOF_PIN7                     7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

#define GPIOG_PIN0                     0U
#define GPIOG_PIN1                     1U
#define GPIOG_PIN2                     2U
#define GPIOG_PIN3                     3U
#define GPIOG_PIN4                     4U
#define GPIOG_PIN5                     5U
#define GPIOG_PIN6                     6U
#define GPIOG_PIN7                     7U
#define GPIOG_PIN8                     8U
#define GPIOG_PIN9                     9U
#define GPIOG_PIN10                    10U
#define GPIOG_PIN11                    11U
#define GPIOG_PIN12                    12U
#define GPIOG_PIN13                    13U
#define GPIOG_PIN14                    14U
#define GPIOG_PIN15                    15U

#define GPIOH_PIN0                     0U
#define GPIOH_PIN1                     1U
#define GPIOH_PIN2                     2U
#define GPIOH_PIN3                     3U
#define GPIOH_PIN4                     4U
#define GPIOH_PIN5                     5U
#define GPIOH_PIN6                     6U
#define GPIOH_PIN7                     7U
#define GPIOH_PIN8                     8U
#define GPIOH_PIN9                     9U
#define GPIOH_PIN10                    10U
#define GPIOH_PIN11                    11U
#define GPIOH_PIN12                    12U
#define GPIOH_PIN13                    13U
#define GPIOH_PIN14                    14U
#define GPIOH_PIN15                    15U

#define GPIOI_PIN0                     0U
#define GPIOI_PIN1                     1U
#define GPIOI_PIN2                     2U
#define GPIOI_PIN3                     3U
#define GPIOI_PIN4                     4U
#define GPIOI_PIN5                     5U
#define GPIOI_PIN6                     6U
#define GPIOI_PIN7                     7U
#define GPIOI_PIN8                     8U
#define GPIOI_PIN9                     9U
#define GPIOI_PIN10                    10U
#define GPIOI_PIN11                    11U
#define GPIOI_PIN12                    12U
#define GPIOI_PIN13                    13U
#define GPIOI_PIN14                    14U
#define GPIOI_PIN15                    15U

/*
    IO lines assignments.
*/

#define LINE_B_TEMP                    PAL_LINE(GPIOB, 1U)
#define LINE_CHG_EN                    PAL_LINE(GPIOB, 2U)
#define LINE_CHG_GOOD                  PAL_LINE(GPIOB, 3U)
#define LINE_GATE                      PAL_LINE(GPIOA, 4U)
#define LINE_GPS_ERR                   PAL_LINE(GPIOA, 9U)
#define LINE_GPS_GD                    PAL_LINE(GPIOA, 8U)
#define LINE_GPS_PPS                   PAL_LINE(GPIOA, 0U)
#define LINE_GPS_RST                   PAL_LINE(GPIOB, 5U)
#define LINE_I2C_SCL                   PAL_LINE(GPIOB, 8U)
#define LINE_I2C_SDA                   PAL_LINE(GPIOB, 9U)
#define LINE_I_CHG_MON                 PAL_LINE(GPIOC, 4U)
#define LINE_OTG_DM                    PAL_LINE(GPIOB, 14U)
#define LINE_OTG_DP                    PAL_LINE(GPIOB, 15U)
#define LINE_OTG_VBUS                  PAL_LINE(GPIOB, 13U)
#define LINE_POWER_GOOD                PAL_LINE(GPIOB, 4U)
#define LINE_PR_ERR                    PAL_LINE(GPIOA, 11U)
#define LINE_PR_GD                     PAL_LINE(GPIOA, 10U)
#define LINE_PR_GPIO                   PAL_LINE(GPIOA, 1U)
#define LINE_PR_NIRQ                   PAL_LINE(GPIOB, 11U)
#define LINE_PR_NSS                    PAL_LINE(GPIOA, 2U)
#define LINE_PR_SDN                    PAL_LINE(GPIOC, 13U)
#define LINE_PR_SW                     PAL_LINE(GPIOC, 1U)
#define LINE_SDIO_CK                   PAL_LINE(GPIOC, 12U)
#define LINE_SDIO_CMD                  PAL_LINE(GPIOD, 2U)
#define LINE_SDIO_D1                   PAL_LINE(GPIOC, 9U)
#define LINE_SDIO_D2                   PAL_LINE(GPIOC, 10U)
#define LINE_SDIO_D3                   PAL_LINE(GPIOC, 11U)
#define LINE_SDIO_DO                   PAL_LINE(GPIOC, 8U)
#define LINE_SPI1_MISO                 PAL_LINE(GPIOA, 6U)
#define LINE_SPI1_MOSI                 PAL_LINE(GPIOA, 7U)
#define LINE_SPI1_SCK                  PAL_LINE(GPIOA, 5U)
#define LINE_SPI2_MISO                 PAL_LINE(GPIOC, 2U)
#define LINE_SPI2_MOSI                 PAL_LINE(GPIOC, 3U)
#define LINE_SPI2_SCK                  PAL_LINE(GPIOB, 10U)
#define LINE_SR_ERR                    PAL_LINE(GPIOA, 15U)
#define LINE_SR_GD                     PAL_LINE(GPIOA, 12U)
#define LINE_SR_NIRQ                   PAL_LINE(GPIOC, 15U)
#define LINE_SR_NSS                    PAL_LINE(GPIOA, 3U)
#define LINE_SR_SDN                    PAL_LINE(GPIOC, 14U)
#define LINE_SR_SW                     PAL_LINE(GPIOC, 0U)
#define LINE_SWCLK                     PAL_LINE(GPIOA, 14U)
#define LINE_SWDIO                     PAL_LINE(GPIOA, 13U)
#define LINE_SYS_ERR                   PAL_LINE(GPIOC, 7U)
#define LINE_SYS_GD                    PAL_LINE(GPIOC, 6U)
#define LINE_UART_RX                   PAL_LINE(GPIOB, 7U)
#define LINE_UART_TX                   PAL_LINE(GPIOB, 6U)
#define LINE_V_BAT_MON                 PAL_LINE(GPIOC, 5U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - GPS_PPS                      (input, pushpull).
 * PA1  - PR_GPIO                      (input, pushpull).
 * PA2  - PR_NSS                       (output, pushpull, starthigh, pullup).
 * PA3  - SR_NSS                       (output, pushpull, starthigh, pullup).
 * PA4  - GATE                         (output, pushpull, startlow, pulldown).
 * PA5  - SPI1_SCK                     (af5).
 * PA6  - SPI1_MISO                    (af5).
 * PA7  - SPI1_MOSI                    (af5).
 * PA8  - GPS_GD                       (output, pushpull, startlow).
 * PA9  - GPS_ERR                      (output, pushpull, startlow).
 * PA10 - PR_GD                        (output, pushpull, startlow).
 * PA11 - PR_ERR                       (output, pushpull, startlow).
 * PA12 - SR_GD                        (output, pushpull, startlow).
 * PA13 - SWDIO                        (af0).
 * PA14 - SWCLK                        (pulldown, af0).
 * PA15 - SR_ERR                       (output, pushpull, startlow).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_INPUT(GPIOA_GPS_PPS) | \
                                        PIN_MODE_INPUT(GPIOA_PR_GPIO) | \
                                        PIN_MODE_OUTPUT(GPIOA_PR_NSS) | \
                                        PIN_MODE_OUTPUT(GPIOA_SR_NSS) | \
                                        PIN_MODE_OUTPUT(GPIOA_GATE) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SPI1_SCK) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SPI1_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SPI1_MOSI) | \
                                        PIN_MODE_OUTPUT(GPIOA_GPS_GD) | \
                                        PIN_MODE_OUTPUT(GPIOA_GPS_ERR) | \
                                        PIN_MODE_OUTPUT(GPIOA_PR_GD) | \
                                        PIN_MODE_OUTPUT(GPIOA_PR_ERR) | \
                                        PIN_MODE_OUTPUT(GPIOA_SR_GD) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWCLK) | \
                                        PIN_MODE_OUTPUT(GPIOA_SR_ERR))
#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_GPS_PPS) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PR_GPIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PR_NSS) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SR_NSS) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GATE) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SPI1_SCK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SPI1_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SPI1_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_GD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_ERR) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PR_GD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PR_ERR) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SR_GD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SR_ERR))
#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_GPS_PPS) | \
                                        PIN_OSPEED_HIGH(GPIOA_PR_GPIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_PR_NSS) | \
                                        PIN_OSPEED_HIGH(GPIOA_SR_NSS) | \
                                        PIN_OSPEED_HIGH(GPIOA_GATE) | \
                                        PIN_OSPEED_HIGH(GPIOA_SPI1_SCK) | \
                                        PIN_OSPEED_HIGH(GPIOA_SPI1_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SPI1_MOSI) | \
                                        PIN_OSPEED_HIGH(GPIOA_GPS_GD) | \
                                        PIN_OSPEED_HIGH(GPIOA_GPS_ERR) | \
                                        PIN_OSPEED_HIGH(GPIOA_PR_GD) | \
                                        PIN_OSPEED_HIGH(GPIOA_PR_ERR) | \
                                        PIN_OSPEED_HIGH(GPIOA_SR_GD) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWCLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_SR_ERR))
#define VAL_GPIOA_PUPDR                (PIN_PUPD_PULLUP(GPIOA_GPS_PPS) | \
                                        PIN_PUPD_PULLUP(GPIOA_PR_GPIO) | \
                                        PIN_PUPD_PULLUP(GPIOA_PR_NSS) | \
                                        PIN_PUPD_PULLUP(GPIOA_SR_NSS) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_GATE) | \
                                        PIN_PUPD_PULLUP(GPIOA_SPI1_SCK) | \
                                        PIN_PUPD_PULLUP(GPIOA_SPI1_MISO) | \
                                        PIN_PUPD_PULLUP(GPIOA_SPI1_MOSI) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_GD) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_ERR) | \
                                        PIN_PUPD_PULLUP(GPIOA_PR_GD) | \
                                        PIN_PUPD_PULLUP(GPIOA_PR_ERR) | \
                                        PIN_PUPD_PULLUP(GPIOA_SR_GD) | \
                                        PIN_PUPD_PULLUP(GPIOA_SWDIO) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_SWCLK) | \
                                        PIN_PUPD_PULLUP(GPIOA_SR_ERR))
#define VAL_GPIOA_ODR                  (PIN_OD_HIGH(GPIOA_GPS_PPS) | \
                                        PIN_OD_HIGH(GPIOA_PR_GPIO) | \
                                        PIN_OD_HIGH(GPIOA_PR_NSS) | \
                                        PIN_OD_HIGH(GPIOA_SR_NSS) | \
                                        PIN_OD_LOW(GPIOA_GATE) | \
                                        PIN_OD_HIGH(GPIOA_SPI1_SCK) | \
                                        PIN_OD_HIGH(GPIOA_SPI1_MISO) | \
                                        PIN_OD_HIGH(GPIOA_SPI1_MOSI) | \
                                        PIN_OD_LOW(GPIOA_GPS_GD) | \
                                        PIN_OD_LOW(GPIOA_GPS_ERR) | \
                                        PIN_OD_LOW(GPIOA_PR_GD) | \
                                        PIN_OD_LOW(GPIOA_PR_ERR) | \
                                        PIN_OD_LOW(GPIOA_SR_GD) | \
                                        PIN_OD_HIGH(GPIOA_SWDIO) | \
                                        PIN_OD_HIGH(GPIOA_SWCLK) | \
                                        PIN_OD_LOW(GPIOA_SR_ERR))
#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_GPS_PPS, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PR_GPIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PR_NSS, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SR_NSS, 0U) | \
                                        PIN_AFIO_AF(GPIOA_GATE, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SPI1_SCK, 5U) | \
                                        PIN_AFIO_AF(GPIOA_SPI1_MISO, 5U) | \
                                        PIN_AFIO_AF(GPIOA_SPI1_MOSI, 5U))
#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_GPS_GD, 0U) | \
                                        PIN_AFIO_AF(GPIOA_GPS_ERR, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PR_GD, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PR_ERR, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SR_GD, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWDIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SR_ERR, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - PIN0                         (unused).
 * PB1  - B_TEMP                       (analog, floating).
 * PB2  - CHG_EN                       (output, pushpull, startlow, pulldown).
 * PB3  - CHG_GOOD                     (input, pushpull).
 * PB4  - POWER_GOOD                   (input, pushpull).
 * PB5  - GPS_RST                      (output, pushpull, starthigh, pullup).
 * PB6  - UART_TX                      (af7).
 * PB7  - UART_RX                      (af7).
 * PB8  - I2C_SCL                      (af4).
 * PB9  - I2C_SDA                      (af4).
 * PB10 - SPI2_SCK                     (af5).
 * PB11 - PR_NIRQ                      (input, pushpull, pullup).
 * PB12 - PIN12                        (unused).
 * PB13 - OTG_VBUS                     (input, pulldown).
 * PB14 - OTG_DM                       (af12).
 * PB15 - OTG_DP                       (af12).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_INPUT(GPIOB_PIN0) | \
                                        PIN_MODE_ANALOG(GPIOB_B_TEMP) | \
                                        PIN_MODE_OUTPUT(GPIOB_CHG_EN) | \
                                        PIN_MODE_INPUT(GPIOB_CHG_GOOD) | \
                                        PIN_MODE_INPUT(GPIOB_POWER_GOOD) | \
                                        PIN_MODE_OUTPUT(GPIOB_GPS_RST) | \
                                        PIN_MODE_ALTERNATE(GPIOB_UART_TX) | \
                                        PIN_MODE_ALTERNATE(GPIOB_UART_RX) | \
                                        PIN_MODE_ALTERNATE(GPIOB_I2C_SCL) | \
                                        PIN_MODE_ALTERNATE(GPIOB_I2C_SDA) | \
                                        PIN_MODE_ALTERNATE(GPIOB_SPI2_SCK) | \
                                        PIN_MODE_INPUT(GPIOB_PR_NIRQ) | \
                                        PIN_MODE_INPUT(GPIOB_PIN12) | \
                                        PIN_MODE_INPUT(GPIOB_OTG_VBUS) | \
                                        PIN_MODE_ALTERNATE(GPIOB_OTG_DM) | \
                                        PIN_MODE_ALTERNATE(GPIOB_OTG_DP))
#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_B_TEMP) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CHG_EN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CHG_GOOD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_POWER_GOOD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_GPS_RST) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_UART_TX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_UART_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_I2C_SCL) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_I2C_SDA) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SPI2_SCK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PR_NIRQ) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_OTG_VBUS) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_OTG_DM) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_OTG_DP))
#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOB_B_TEMP) | \
                                        PIN_OSPEED_HIGH(GPIOB_CHG_EN) | \
                                        PIN_OSPEED_HIGH(GPIOB_CHG_GOOD) | \
                                        PIN_OSPEED_HIGH(GPIOB_POWER_GOOD) | \
                                        PIN_OSPEED_HIGH(GPIOB_GPS_RST) | \
                                        PIN_OSPEED_HIGH(GPIOB_UART_TX) | \
                                        PIN_OSPEED_HIGH(GPIOB_UART_RX) | \
                                        PIN_OSPEED_HIGH(GPIOB_I2C_SCL) | \
                                        PIN_OSPEED_HIGH(GPIOB_I2C_SDA) | \
                                        PIN_OSPEED_HIGH(GPIOB_SPI2_SCK) | \
                                        PIN_OSPEED_HIGH(GPIOB_PR_NIRQ) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOB_OTG_VBUS) | \
                                        PIN_OSPEED_HIGH(GPIOB_OTG_DM) | \
                                        PIN_OSPEED_HIGH(GPIOB_OTG_DP))
#define VAL_GPIOB_PUPDR                (PIN_PUPD_PULLUP(GPIOB_PIN0) | \
                                        PIN_PUPD_FLOATING(GPIOB_B_TEMP) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_CHG_EN) | \
                                        PIN_PUPD_PULLUP(GPIOB_CHG_GOOD) | \
                                        PIN_PUPD_PULLUP(GPIOB_POWER_GOOD) | \
                                        PIN_PUPD_PULLUP(GPIOB_GPS_RST) | \
                                        PIN_PUPD_PULLUP(GPIOB_UART_TX) | \
                                        PIN_PUPD_PULLUP(GPIOB_UART_RX) | \
                                        PIN_PUPD_PULLUP(GPIOB_I2C_SCL) | \
                                        PIN_PUPD_PULLUP(GPIOB_I2C_SDA) | \
                                        PIN_PUPD_PULLUP(GPIOB_SPI2_SCK) | \
                                        PIN_PUPD_PULLUP(GPIOB_PR_NIRQ) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN12) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_OTG_VBUS) | \
                                        PIN_PUPD_PULLUP(GPIOB_OTG_DM) | \
                                        PIN_PUPD_PULLUP(GPIOB_OTG_DP))
#define VAL_GPIOB_ODR                  (PIN_OD_HIGH(GPIOB_PIN0) | \
                                        PIN_OD_HIGH(GPIOB_B_TEMP) | \
                                        PIN_OD_LOW(GPIOB_CHG_EN) | \
                                        PIN_OD_HIGH(GPIOB_CHG_GOOD) | \
                                        PIN_OD_HIGH(GPIOB_POWER_GOOD) | \
                                        PIN_OD_HIGH(GPIOB_GPS_RST) | \
                                        PIN_OD_HIGH(GPIOB_UART_TX) | \
                                        PIN_OD_HIGH(GPIOB_UART_RX) | \
                                        PIN_OD_HIGH(GPIOB_I2C_SCL) | \
                                        PIN_OD_HIGH(GPIOB_I2C_SDA) | \
                                        PIN_OD_HIGH(GPIOB_SPI2_SCK) | \
                                        PIN_OD_HIGH(GPIOB_PR_NIRQ) | \
                                        PIN_OD_HIGH(GPIOB_PIN12) | \
                                        PIN_OD_HIGH(GPIOB_OTG_VBUS) | \
                                        PIN_OD_HIGH(GPIOB_OTG_DM) | \
                                        PIN_OD_HIGH(GPIOB_OTG_DP))
#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOB_B_TEMP, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CHG_EN, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CHG_GOOD, 0U) | \
                                        PIN_AFIO_AF(GPIOB_POWER_GOOD, 0U) | \
                                        PIN_AFIO_AF(GPIOB_GPS_RST, 0U) | \
                                        PIN_AFIO_AF(GPIOB_UART_TX, 7U) | \
                                        PIN_AFIO_AF(GPIOB_UART_RX, 7U))
#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_I2C_SCL, 4U) | \
                                        PIN_AFIO_AF(GPIOB_I2C_SDA, 4U) | \
                                        PIN_AFIO_AF(GPIOB_SPI2_SCK, 5U) | \
                                        PIN_AFIO_AF(GPIOB_PR_NIRQ, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOB_OTG_VBUS, 0U) | \
                                        PIN_AFIO_AF(GPIOB_OTG_DM, 12U) | \
                                        PIN_AFIO_AF(GPIOB_OTG_DP, 12U))

/*
 *  GPIOC setup:
 *
 * PC0  - SR_SW                        (output, pushpull).
 * PC1  - PR_SW                        (output, pushpull).
 * PC2  - SPI2_MISO                    (af5).
 * PC3  - SPI2_MOSI                    (af5).
 * PC4  - I_CHG_MON                    (analog, floating).
 * PC5  - V_BAT_MON                    (analog, floating).
 * PC6  - SYS_GD                       (output, pushpull, startlow).
 * PC7  - SYS_ERR                      (output, pushpull, startlow).
 * PC8  - SDIO_DO                      (af12).
 * PC9  - SDIO_D1                      (af12).
 * PC10 - SDIO_D2                      (af12).
 * PC11 - SDIO_D3                      (af12).
 * PC12 - SDIO_CK                      (af12).
 * PC13 - PR_SDN                       (output, pushpull).
 * PC14 - SR_SDN                       (output, pushpull).
 * PC15 - SR_NIRQ                      (input, pushpull, pullup).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_OUTPUT(GPIOC_SR_SW) | \
                                        PIN_MODE_OUTPUT(GPIOC_PR_SW) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SPI2_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SPI2_MOSI) | \
                                        PIN_MODE_ANALOG(GPIOC_I_CHG_MON) | \
                                        PIN_MODE_ANALOG(GPIOC_V_BAT_MON) | \
                                        PIN_MODE_OUTPUT(GPIOC_SYS_GD) | \
                                        PIN_MODE_OUTPUT(GPIOC_SYS_ERR) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SDIO_DO) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SDIO_D1) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SDIO_D2) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SDIO_D3) | \
                                        PIN_MODE_ALTERNATE(GPIOC_SDIO_CK) | \
                                        PIN_MODE_OUTPUT(GPIOC_PR_SDN) | \
                                        PIN_MODE_OUTPUT(GPIOC_SR_SDN) | \
                                        PIN_MODE_INPUT(GPIOC_SR_NIRQ))
#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_SR_SW) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PR_SW) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SPI2_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SPI2_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_I_CHG_MON) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_V_BAT_MON) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SYS_GD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SYS_ERR) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SDIO_DO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SDIO_D1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SDIO_D2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SDIO_D3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SDIO_CK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PR_SDN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SR_SDN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_SR_NIRQ))
#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_SR_SW) | \
                                        PIN_OSPEED_HIGH(GPIOC_PR_SW) | \
                                        PIN_OSPEED_HIGH(GPIOC_SPI2_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOC_SPI2_MOSI) | \
                                        PIN_OSPEED_HIGH(GPIOC_I_CHG_MON) | \
                                        PIN_OSPEED_HIGH(GPIOC_V_BAT_MON) | \
                                        PIN_OSPEED_HIGH(GPIOC_SYS_GD) | \
                                        PIN_OSPEED_HIGH(GPIOC_SYS_ERR) | \
                                        PIN_OSPEED_HIGH(GPIOC_SDIO_DO) | \
                                        PIN_OSPEED_HIGH(GPIOC_SDIO_D1) | \
                                        PIN_OSPEED_HIGH(GPIOC_SDIO_D2) | \
                                        PIN_OSPEED_HIGH(GPIOC_SDIO_D3) | \
                                        PIN_OSPEED_HIGH(GPIOC_SDIO_CK) | \
                                        PIN_OSPEED_HIGH(GPIOC_PR_SDN) | \
                                        PIN_OSPEED_HIGH(GPIOC_SR_SDN) | \
                                        PIN_OSPEED_HIGH(GPIOC_SR_NIRQ))
#define VAL_GPIOC_PUPDR                (PIN_PUPD_PULLUP(GPIOC_SR_SW) | \
                                        PIN_PUPD_PULLUP(GPIOC_PR_SW) | \
                                        PIN_PUPD_PULLUP(GPIOC_SPI2_MISO) | \
                                        PIN_PUPD_PULLUP(GPIOC_SPI2_MOSI) | \
                                        PIN_PUPD_FLOATING(GPIOC_I_CHG_MON) | \
                                        PIN_PUPD_FLOATING(GPIOC_V_BAT_MON) | \
                                        PIN_PUPD_PULLUP(GPIOC_SYS_GD) | \
                                        PIN_PUPD_PULLUP(GPIOC_SYS_ERR) | \
                                        PIN_PUPD_PULLUP(GPIOC_SDIO_DO) | \
                                        PIN_PUPD_PULLUP(GPIOC_SDIO_D1) | \
                                        PIN_PUPD_PULLUP(GPIOC_SDIO_D2) | \
                                        PIN_PUPD_PULLUP(GPIOC_SDIO_D3) | \
                                        PIN_PUPD_PULLUP(GPIOC_SDIO_CK) | \
                                        PIN_PUPD_PULLUP(GPIOC_PR_SDN) | \
                                        PIN_PUPD_PULLUP(GPIOC_SR_SDN) | \
                                        PIN_PUPD_PULLUP(GPIOC_SR_NIRQ))
#define VAL_GPIOC_ODR                  (PIN_OD_HIGH(GPIOC_SR_SW) | \
                                        PIN_OD_HIGH(GPIOC_PR_SW) | \
                                        PIN_OD_HIGH(GPIOC_SPI2_MISO) | \
                                        PIN_OD_HIGH(GPIOC_SPI2_MOSI) | \
                                        PIN_OD_HIGH(GPIOC_I_CHG_MON) | \
                                        PIN_OD_HIGH(GPIOC_V_BAT_MON) | \
                                        PIN_OD_LOW(GPIOC_SYS_GD) | \
                                        PIN_OD_LOW(GPIOC_SYS_ERR) | \
                                        PIN_OD_HIGH(GPIOC_SDIO_DO) | \
                                        PIN_OD_HIGH(GPIOC_SDIO_D1) | \
                                        PIN_OD_HIGH(GPIOC_SDIO_D2) | \
                                        PIN_OD_HIGH(GPIOC_SDIO_D3) | \
                                        PIN_OD_HIGH(GPIOC_SDIO_CK) | \
                                        PIN_OD_HIGH(GPIOC_PR_SDN) | \
                                        PIN_OD_HIGH(GPIOC_SR_SDN) | \
                                        PIN_OD_HIGH(GPIOC_SR_NIRQ))
#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_SR_SW, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PR_SW, 0U) | \
                                        PIN_AFIO_AF(GPIOC_SPI2_MISO, 5U) | \
                                        PIN_AFIO_AF(GPIOC_SPI2_MOSI, 5U) | \
                                        PIN_AFIO_AF(GPIOC_I_CHG_MON, 0U) | \
                                        PIN_AFIO_AF(GPIOC_V_BAT_MON, 0U) | \
                                        PIN_AFIO_AF(GPIOC_SYS_GD, 0U) | \
                                        PIN_AFIO_AF(GPIOC_SYS_ERR, 0U))
#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_SDIO_DO, 12U) | \
                                        PIN_AFIO_AF(GPIOC_SDIO_D1, 12U) | \
                                        PIN_AFIO_AF(GPIOC_SDIO_D2, 12U) | \
                                        PIN_AFIO_AF(GPIOC_SDIO_D3, 12U) | \
                                        PIN_AFIO_AF(GPIOC_SDIO_CK, 12U) | \
                                        PIN_AFIO_AF(GPIOC_PR_SDN, 0U) | \
                                        PIN_AFIO_AF(GPIOC_SR_SDN, 0U) | \
                                        PIN_AFIO_AF(GPIOC_SR_NIRQ, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - SDIO_CMD                     (af12).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_ALTERNATE(GPIOD_SDIO_CMD) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))
#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_SDIO_CMD) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))
#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_SDIO_CMD) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLUP(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOD_SDIO_CMD) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN15))
#define VAL_GPIOD_ODR                  (PIN_OD_HIGH(GPIOD_PIN0) | \
                                        PIN_OD_HIGH(GPIOD_PIN1) | \
                                        PIN_OD_HIGH(GPIOD_SDIO_CMD) | \
                                        PIN_OD_HIGH(GPIOD_PIN3) | \
                                        PIN_OD_HIGH(GPIOD_PIN4) | \
                                        PIN_OD_HIGH(GPIOD_PIN5) | \
                                        PIN_OD_HIGH(GPIOD_PIN6) | \
                                        PIN_OD_HIGH(GPIOD_PIN7) | \
                                        PIN_OD_HIGH(GPIOD_PIN8) | \
                                        PIN_OD_HIGH(GPIOD_PIN9) | \
                                        PIN_OD_HIGH(GPIOD_PIN10) | \
                                        PIN_OD_HIGH(GPIOD_PIN11) | \
                                        PIN_OD_HIGH(GPIOD_PIN12) | \
                                        PIN_OD_HIGH(GPIOD_PIN13) | \
                                        PIN_OD_HIGH(GPIOD_PIN14) | \
                                        PIN_OD_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_SDIO_CMD, 12U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))
#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOE setup:
 *
 * PE0  - PIN0                         (unused).
 * PE1  - PIN1                         (unused).
 * PE2  - PIN2                         (unused).
 * PE3  - PIN3                         (unused).
 * PE4  - PIN4                         (unused).
 * PE5  - PIN5                         (unused).
 * PE6  - PIN6                         (unused).
 * PE7  - PIN7                         (unused).
 * PE8  - PIN8                         (unused).
 * PE9  - PIN9                         (unused).
 * PE10 - PIN10                        (unused).
 * PE11 - PIN11                        (unused).
 * PE12 - PIN12                        (unused).
 * PE13 - PIN13                        (unused).
 * PE14 - PIN14                        (unused).
 * PE15 - PIN15                        (unused).
*/
#define VAL_GPIOE_MODER                (PIN_MODE_INPUT(GPIOE_PIN0) | \
                                        PIN_MODE_INPUT(GPIOE_PIN1) | \
                                        PIN_MODE_INPUT(GPIOE_PIN2) | \
                                        PIN_MODE_INPUT(GPIOE_PIN3) | \
                                        PIN_MODE_INPUT(GPIOE_PIN4) | \
                                        PIN_MODE_INPUT(GPIOE_PIN5) | \
                                        PIN_MODE_INPUT(GPIOE_PIN6) | \
                                        PIN_MODE_INPUT(GPIOE_PIN7) | \
                                        PIN_MODE_INPUT(GPIOE_PIN8) | \
                                        PIN_MODE_INPUT(GPIOE_PIN9) | \
                                        PIN_MODE_INPUT(GPIOE_PIN10) | \
                                        PIN_MODE_INPUT(GPIOE_PIN11) | \
                                        PIN_MODE_INPUT(GPIOE_PIN12) | \
                                        PIN_MODE_INPUT(GPIOE_PIN13) | \
                                        PIN_MODE_INPUT(GPIOE_PIN14) | \
                                        PIN_MODE_INPUT(GPIOE_PIN15))
#define VAL_GPIOE_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOE_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN15))
#define VAL_GPIOE_OSPEEDR              (PIN_OSPEED_HIGH(GPIOE_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN15))
#define VAL_GPIOE_PUPDR                (PIN_PUPD_PULLUP(GPIOE_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN15))
#define VAL_GPIOE_ODR                  (PIN_OD_HIGH(GPIOE_PIN0) | \
                                        PIN_OD_HIGH(GPIOE_PIN1) | \
                                        PIN_OD_HIGH(GPIOE_PIN2) | \
                                        PIN_OD_HIGH(GPIOE_PIN3) | \
                                        PIN_OD_HIGH(GPIOE_PIN4) | \
                                        PIN_OD_HIGH(GPIOE_PIN5) | \
                                        PIN_OD_HIGH(GPIOE_PIN6) | \
                                        PIN_OD_HIGH(GPIOE_PIN7) | \
                                        PIN_OD_HIGH(GPIOE_PIN8) | \
                                        PIN_OD_HIGH(GPIOE_PIN9) | \
                                        PIN_OD_HIGH(GPIOE_PIN10) | \
                                        PIN_OD_HIGH(GPIOE_PIN11) | \
                                        PIN_OD_HIGH(GPIOE_PIN12) | \
                                        PIN_OD_HIGH(GPIOE_PIN13) | \
                                        PIN_OD_HIGH(GPIOE_PIN14) | \
                                        PIN_OD_HIGH(GPIOE_PIN15))
#define VAL_GPIOE_AFRL                 (PIN_AFIO_AF(GPIOE_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN7, 0U))
#define VAL_GPIOE_AFRH                 (PIN_AFIO_AF(GPIOE_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN15, 0U))

/*
 *  GPIOF setup:
 *
 * PF0  - PIN0                         (unused).
 * PF1  - PIN1                         (unused).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - PIN6                         (unused).
 * PF7  - PIN7                         (unused).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_INPUT(GPIOF_PIN0) | \
                                        PIN_MODE_INPUT(GPIOF_PIN1) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_PIN6) | \
                                        PIN_MODE_INPUT(GPIOF_PIN7) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))
#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))
#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_PUPDR                (PIN_PUPD_PULLUP(GPIOF_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN15))
#define VAL_GPIOF_ODR                  (PIN_OD_HIGH(GPIOF_PIN0) | \
                                        PIN_OD_HIGH(GPIOF_PIN1) | \
                                        PIN_OD_HIGH(GPIOF_PIN2) | \
                                        PIN_OD_HIGH(GPIOF_PIN3) | \
                                        PIN_OD_HIGH(GPIOF_PIN4) | \
                                        PIN_OD_HIGH(GPIOF_PIN5) | \
                                        PIN_OD_HIGH(GPIOF_PIN6) | \
                                        PIN_OD_HIGH(GPIOF_PIN7) | \
                                        PIN_OD_HIGH(GPIOF_PIN8) | \
                                        PIN_OD_HIGH(GPIOF_PIN9) | \
                                        PIN_OD_HIGH(GPIOF_PIN10) | \
                                        PIN_OD_HIGH(GPIOF_PIN11) | \
                                        PIN_OD_HIGH(GPIOF_PIN12) | \
                                        PIN_OD_HIGH(GPIOF_PIN13) | \
                                        PIN_OD_HIGH(GPIOF_PIN14) | \
                                        PIN_OD_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN7, 0U))
#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

/*
 *  GPIOG setup:
 *
 * PG0  - PIN0                         (unused).
 * PG1  - PIN1                         (unused).
 * PG2  - PIN2                         (unused).
 * PG3  - PIN3                         (unused).
 * PG4  - PIN4                         (unused).
 * PG5  - PIN5                         (unused).
 * PG6  - PIN6                         (unused).
 * PG7  - PIN7                         (unused).
 * PG8  - PIN8                         (unused).
 * PG9  - PIN9                         (unused).
 * PG10 - PIN10                        (unused).
 * PG11 - PIN11                        (unused).
 * PG12 - PIN12                        (unused).
 * PG13 - PIN13                        (unused).
 * PG14 - PIN14                        (unused).
 * PG15 - PIN15                        (unused).
*/
#define VAL_GPIOG_MODER                (PIN_MODE_INPUT(GPIOG_PIN0) | \
                                        PIN_MODE_INPUT(GPIOG_PIN1) | \
                                        PIN_MODE_INPUT(GPIOG_PIN2) | \
                                        PIN_MODE_INPUT(GPIOG_PIN3) | \
                                        PIN_MODE_INPUT(GPIOG_PIN4) | \
                                        PIN_MODE_INPUT(GPIOG_PIN5) | \
                                        PIN_MODE_INPUT(GPIOG_PIN6) | \
                                        PIN_MODE_INPUT(GPIOG_PIN7) | \
                                        PIN_MODE_INPUT(GPIOG_PIN8) | \
                                        PIN_MODE_INPUT(GPIOG_PIN9) | \
                                        PIN_MODE_INPUT(GPIOG_PIN10) | \
                                        PIN_MODE_INPUT(GPIOG_PIN11) | \
                                        PIN_MODE_INPUT(GPIOG_PIN12) | \
                                        PIN_MODE_INPUT(GPIOG_PIN13) | \
                                        PIN_MODE_INPUT(GPIOG_PIN14) | \
                                        PIN_MODE_INPUT(GPIOG_PIN15))
#define VAL_GPIOG_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOG_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN15))
#define VAL_GPIOG_OSPEEDR              (PIN_OSPEED_HIGH(GPIOG_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN15))
#define VAL_GPIOG_PUPDR                (PIN_PUPD_PULLUP(GPIOG_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN15))
#define VAL_GPIOG_ODR                  (PIN_OD_HIGH(GPIOG_PIN0) | \
                                        PIN_OD_HIGH(GPIOG_PIN1) | \
                                        PIN_OD_HIGH(GPIOG_PIN2) | \
                                        PIN_OD_HIGH(GPIOG_PIN3) | \
                                        PIN_OD_HIGH(GPIOG_PIN4) | \
                                        PIN_OD_HIGH(GPIOG_PIN5) | \
                                        PIN_OD_HIGH(GPIOG_PIN6) | \
                                        PIN_OD_HIGH(GPIOG_PIN7) | \
                                        PIN_OD_HIGH(GPIOG_PIN8) | \
                                        PIN_OD_HIGH(GPIOG_PIN9) | \
                                        PIN_OD_HIGH(GPIOG_PIN10) | \
                                        PIN_OD_HIGH(GPIOG_PIN11) | \
                                        PIN_OD_HIGH(GPIOG_PIN12) | \
                                        PIN_OD_HIGH(GPIOG_PIN13) | \
                                        PIN_OD_HIGH(GPIOG_PIN14) | \
                                        PIN_OD_HIGH(GPIOG_PIN15))
#define VAL_GPIOG_AFRL                 (PIN_AFIO_AF(GPIOG_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN7, 0U))
#define VAL_GPIOG_AFRH                 (PIN_AFIO_AF(GPIOG_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN15, 0U))

/*
 *  GPIOH setup:
 *
 * PH0  - PIN0                         (unused).
 * PH1  - PIN1                         (unused).
 * PH2  - PIN2                         (unused).
 * PH3  - PIN3                         (unused).
 * PH4  - PIN4                         (unused).
 * PH5  - PIN5                         (unused).
 * PH6  - PIN6                         (unused).
 * PH7  - PIN7                         (unused).
 * PH8  - PIN8                         (unused).
 * PH9  - PIN9                         (unused).
 * PH10 - PIN10                        (unused).
 * PH11 - PIN11                        (unused).
 * PH12 - PIN12                        (unused).
 * PH13 - PIN13                        (unused).
 * PH14 - PIN14                        (unused).
 * PH15 - PIN15                        (unused).
*/
#define VAL_GPIOH_MODER                (PIN_MODE_INPUT(GPIOH_PIN0) | \
                                        PIN_MODE_INPUT(GPIOH_PIN1) | \
                                        PIN_MODE_INPUT(GPIOH_PIN2) | \
                                        PIN_MODE_INPUT(GPIOH_PIN3) | \
                                        PIN_MODE_INPUT(GPIOH_PIN4) | \
                                        PIN_MODE_INPUT(GPIOH_PIN5) | \
                                        PIN_MODE_INPUT(GPIOH_PIN6) | \
                                        PIN_MODE_INPUT(GPIOH_PIN7) | \
                                        PIN_MODE_INPUT(GPIOH_PIN8) | \
                                        PIN_MODE_INPUT(GPIOH_PIN9) | \
                                        PIN_MODE_INPUT(GPIOH_PIN10) | \
                                        PIN_MODE_INPUT(GPIOH_PIN11) | \
                                        PIN_MODE_INPUT(GPIOH_PIN12) | \
                                        PIN_MODE_INPUT(GPIOH_PIN13) | \
                                        PIN_MODE_INPUT(GPIOH_PIN14) | \
                                        PIN_MODE_INPUT(GPIOH_PIN15))
#define VAL_GPIOH_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOH_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN15))
#define VAL_GPIOH_OSPEEDR              (PIN_OSPEED_HIGH(GPIOH_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN15))
#define VAL_GPIOH_PUPDR                (PIN_PUPD_PULLUP(GPIOH_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN15))
#define VAL_GPIOH_ODR                  (PIN_OD_HIGH(GPIOH_PIN0) | \
                                        PIN_OD_HIGH(GPIOH_PIN1) | \
                                        PIN_OD_HIGH(GPIOH_PIN2) | \
                                        PIN_OD_HIGH(GPIOH_PIN3) | \
                                        PIN_OD_HIGH(GPIOH_PIN4) | \
                                        PIN_OD_HIGH(GPIOH_PIN5) | \
                                        PIN_OD_HIGH(GPIOH_PIN6) | \
                                        PIN_OD_HIGH(GPIOH_PIN7) | \
                                        PIN_OD_HIGH(GPIOH_PIN8) | \
                                        PIN_OD_HIGH(GPIOH_PIN9) | \
                                        PIN_OD_HIGH(GPIOH_PIN10) | \
                                        PIN_OD_HIGH(GPIOH_PIN11) | \
                                        PIN_OD_HIGH(GPIOH_PIN12) | \
                                        PIN_OD_HIGH(GPIOH_PIN13) | \
                                        PIN_OD_HIGH(GPIOH_PIN14) | \
                                        PIN_OD_HIGH(GPIOH_PIN15))
#define VAL_GPIOH_AFRL                 (PIN_AFIO_AF(GPIOH_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN7, 0U))
#define VAL_GPIOH_AFRH                 (PIN_AFIO_AF(GPIOH_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN15, 0U))

/*
 *  GPIOI setup:
 *
 * PI0  - PIN0                         (unused).
 * PI1  - PIN1                         (unused).
 * PI2  - PIN2                         (unused).
 * PI3  - PIN3                         (unused).
 * PI4  - PIN4                         (unused).
 * PI5  - PIN5                         (unused).
 * PI6  - PIN6                         (unused).
 * PI7  - PIN7                         (unused).
 * PI8  - PIN8                         (unused).
 * PI9  - PIN9                         (unused).
 * PI10 - PIN10                        (unused).
 * PI11 - PIN11                        (unused).
 * PI12 - PIN12                        (unused).
 * PI13 - PIN13                        (unused).
 * PI14 - PIN14                        (unused).
 * PI15 - PIN15                        (unused).
*/
#define VAL_GPIOI_MODER                (PIN_MODE_INPUT(GPIOI_PIN0) | \
                                        PIN_MODE_INPUT(GPIOI_PIN1) | \
                                        PIN_MODE_INPUT(GPIOI_PIN2) | \
                                        PIN_MODE_INPUT(GPIOI_PIN3) | \
                                        PIN_MODE_INPUT(GPIOI_PIN4) | \
                                        PIN_MODE_INPUT(GPIOI_PIN5) | \
                                        PIN_MODE_INPUT(GPIOI_PIN6) | \
                                        PIN_MODE_INPUT(GPIOI_PIN7) | \
                                        PIN_MODE_INPUT(GPIOI_PIN8) | \
                                        PIN_MODE_INPUT(GPIOI_PIN9) | \
                                        PIN_MODE_INPUT(GPIOI_PIN10) | \
                                        PIN_MODE_INPUT(GPIOI_PIN11) | \
                                        PIN_MODE_INPUT(GPIOI_PIN12) | \
                                        PIN_MODE_INPUT(GPIOI_PIN13) | \
                                        PIN_MODE_INPUT(GPIOI_PIN14) | \
                                        PIN_MODE_INPUT(GPIOI_PIN15))
#define VAL_GPIOI_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOI_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN15))
#define VAL_GPIOI_OSPEEDR              (PIN_OSPEED_HIGH(GPIOI_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN15))
#define VAL_GPIOI_PUPDR                (PIN_PUPD_PULLUP(GPIOI_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN15))
#define VAL_GPIOI_ODR                  (PIN_OD_HIGH(GPIOI_PIN0) | \
                                        PIN_OD_HIGH(GPIOI_PIN1) | \
                                        PIN_OD_HIGH(GPIOI_PIN2) | \
                                        PIN_OD_HIGH(GPIOI_PIN3) | \
                                        PIN_OD_HIGH(GPIOI_PIN4) | \
                                        PIN_OD_HIGH(GPIOI_PIN5) | \
                                        PIN_OD_HIGH(GPIOI_PIN6) | \
                                        PIN_OD_HIGH(GPIOI_PIN7) | \
                                        PIN_OD_HIGH(GPIOI_PIN8) | \
                                        PIN_OD_HIGH(GPIOI_PIN9) | \
                                        PIN_OD_HIGH(GPIOI_PIN10) | \
                                        PIN_OD_HIGH(GPIOI_PIN11) | \
                                        PIN_OD_HIGH(GPIOI_PIN12) | \
                                        PIN_OD_HIGH(GPIOI_PIN13) | \
                                        PIN_OD_HIGH(GPIOI_PIN14) | \
                                        PIN_OD_HIGH(GPIOI_PIN15))
#define VAL_GPIOI_AFRL                 (PIN_AFIO_AF(GPIOI_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN7, 0U))
#define VAL_GPIOI_AFRH                 (PIN_AFIO_AF(GPIOI_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
