#ifndef M3PYRO_STATUS_H
#define M3PYRO_STATUS_H

#define M3PYRO_COMPONENT_CONTINUITY (1)
#define M3PYRO_COMPONENT_ARMING     (2)
#define M3PYRO_COMPONENT_FIRING     (3)

#define M3PYRO_ERROR_ADC            (1)

#endif
