/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for extpressure
*/

/*
    Board identifier
*/
#define BOARD_EXTPRESSURE
#define BOARD_NAME                     "extpressure"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   0U
#endif

#define STM32_LSEDRV (3<<3)
#define STM32_HSEBYPASS

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F051x8

/*
    IO pins assignments.
*/

#define GPIOA_PIN0                     0U
#define GPIOA_PIN1                     1U
#define GPIOA_PIN2                     2U
#define GPIOA_CS4                      3U
#define GPIOA_LED_GRN                  4U
#define GPIOA_SCLK                     5U
#define GPIOA_MISO                     6U
#define GPIOA_MOSI                     7U
#define GPIOA_PIN8                     8U
#define GPIOA_TX                       9U
#define GPIOA_RX                       10U
#define GPIOA_PIN11                    11U
#define GPIOA_PIN12                    12U
#define GPIOA_SWDIO                    13U
#define GPIOA_SWCLK                    14U
#define GPIOA_CS1                      15U

#define GPIOB_PIN0                     0U
#define GPIOB_CS2                      1U
#define GPIOB_PIN2                     2U
#define GPIOB_CS3                      3U
#define GPIOB_PIN4                     4U
#define GPIOB_PIN5                     5U
#define GPIOB_LED_RED                  6U
#define GPIOB_PIN7                     7U
#define GPIOB_PIN8                     8U
#define GPIOB_PIN9                     9U
#define GPIOB_PIN10                    10U
#define GPIOB_PIN11                    11U
#define GPIOB_PIN12                    12U
#define GPIOB_PIN13                    13U
#define GPIOB_PIN14                    14U
#define GPIOB_PIN15                    15U

#define GPIOC_PIN0                     0U
#define GPIOC_PIN1                     1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_PIN4                     4U
#define GPIOC_PIN5                     5U
#define GPIOC_PIN6                     6U
#define GPIOC_PIN7                     7U
#define GPIOC_PIN8                     8U
#define GPIOC_PIN9                     9U
#define GPIOC_PIN10                    10U
#define GPIOC_PIN11                    11U
#define GPIOC_PIN12                    12U
#define GPIOC_PIN13                    13U
#define GPIOC_PIN14                    14U
#define GPIOC_PIN15                    15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOF_PIN0                     0U
#define GPIOF_PIN1                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_PIN6                     6U
#define GPIOF_PIN7                     7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

/*
    IO lines assignments.
*/

#define LINE_CS1                       PAL_LINE(GPIOA, 15U)
#define LINE_CS2                       PAL_LINE(GPIOB, 1U)
#define LINE_CS3                       PAL_LINE(GPIOB, 3U)
#define LINE_CS4                       PAL_LINE(GPIOA, 3U)
#define LINE_LED_GRN                   PAL_LINE(GPIOA, 4U)
#define LINE_LED_RED                   PAL_LINE(GPIOB, 6U)
#define LINE_MISO                      PAL_LINE(GPIOA, 6U)
#define LINE_MOSI                      PAL_LINE(GPIOA, 7U)
#define LINE_RX                        PAL_LINE(GPIOA, 10U)
#define LINE_SCLK                      PAL_LINE(GPIOA, 5U)
#define LINE_SWCLK                     PAL_LINE(GPIOA, 14U)
#define LINE_SWDIO                     PAL_LINE(GPIOA, 13U)
#define LINE_TX                        PAL_LINE(GPIOA, 9U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - PIN0                         (unused).
 * PA1  - PIN1                         (unused).
 * PA2  - PIN2                         (unused).
 * PA3  - CS4                          (output, floating).
 * PA4  - LED_GRN                      (output, startlow, floating).
 * PA5  - SCLK                         (af0).
 * PA6  - MISO                         (af0).
 * PA7  - MOSI                         (af0).
 * PA8  - PIN8                         (unused).
 * PA9  - TX                           (af1).
 * PA10 - RX                           (af1).
 * PA11 - PIN11                        (unused).
 * PA12 - PIN12                        (unused).
 * PA13 - SWDIO                        (af0).
 * PA14 - SWCLK                        (af0, pulldown).
 * PA15 - CS1                          (output, floating).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_INPUT(GPIOA_PIN0) | \
                                        PIN_MODE_INPUT(GPIOA_PIN1) | \
                                        PIN_MODE_INPUT(GPIOA_PIN2) | \
                                        PIN_MODE_OUTPUT(GPIOA_CS4) | \
                                        PIN_MODE_OUTPUT(GPIOA_LED_GRN) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SCLK) | \
                                        PIN_MODE_ALTERNATE(GPIOA_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_MOSI) | \
                                        PIN_MODE_INPUT(GPIOA_PIN8) | \
                                        PIN_MODE_ALTERNATE(GPIOA_TX) | \
                                        PIN_MODE_ALTERNATE(GPIOA_RX) | \
                                        PIN_MODE_INPUT(GPIOA_PIN11) | \
                                        PIN_MODE_INPUT(GPIOA_PIN12) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWCLK) | \
                                        PIN_MODE_OUTPUT(GPIOA_CS1))
#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_CS4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LED_GRN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_TX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_CS1))
#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOA_CS4) | \
                                        PIN_OSPEED_HIGH(GPIOA_LED_GRN) | \
                                        PIN_OSPEED_HIGH(GPIOA_SCLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOA_MOSI) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOA_TX) | \
                                        PIN_OSPEED_HIGH(GPIOA_RX) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWCLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_CS1))
#define VAL_GPIOA_PUPDR                (PIN_PUPD_PULLUP(GPIOA_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN2) | \
                                        PIN_PUPD_FLOATING(GPIOA_CS4) | \
                                        PIN_PUPD_FLOATING(GPIOA_LED_GRN) | \
                                        PIN_PUPD_PULLUP(GPIOA_SCLK) | \
                                        PIN_PUPD_PULLUP(GPIOA_MISO) | \
                                        PIN_PUPD_PULLUP(GPIOA_MOSI) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOA_TX) | \
                                        PIN_PUPD_PULLUP(GPIOA_RX) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOA_SWDIO) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_SWCLK) | \
                                        PIN_PUPD_FLOATING(GPIOA_CS1))
#define VAL_GPIOA_ODR                  (PIN_OD_HIGH(GPIOA_PIN0) | \
                                        PIN_OD_HIGH(GPIOA_PIN1) | \
                                        PIN_OD_HIGH(GPIOA_PIN2) | \
                                        PIN_OD_HIGH(GPIOA_CS4) | \
                                        PIN_OD_LOW(GPIOA_LED_GRN) | \
                                        PIN_OD_HIGH(GPIOA_SCLK) | \
                                        PIN_OD_HIGH(GPIOA_MISO) | \
                                        PIN_OD_HIGH(GPIOA_MOSI) | \
                                        PIN_OD_HIGH(GPIOA_PIN8) | \
                                        PIN_OD_HIGH(GPIOA_TX) | \
                                        PIN_OD_HIGH(GPIOA_RX) | \
                                        PIN_OD_HIGH(GPIOA_PIN11) | \
                                        PIN_OD_HIGH(GPIOA_PIN12) | \
                                        PIN_OD_HIGH(GPIOA_SWDIO) | \
                                        PIN_OD_HIGH(GPIOA_SWCLK) | \
                                        PIN_OD_HIGH(GPIOA_CS1))
#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_CS4, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LED_GRN, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_MISO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_MOSI, 0U))
#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOA_TX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_RX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWDIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_CS1, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - PIN0                         (unused).
 * PB1  - CS2                          (output, floating).
 * PB2  - PIN2                         (unused).
 * PB3  - CS3                          (output, floating).
 * PB4  - PIN4                         (unused).
 * PB5  - PIN5                         (unused).
 * PB6  - LED_RED                      (output, startlow, floating).
 * PB7  - PIN7                         (unused).
 * PB8  - PIN8                         (unused).
 * PB9  - PIN9                         (unused).
 * PB10 - PIN10                        (unused).
 * PB11 - PIN11                        (unused).
 * PB12 - PIN12                        (unused).
 * PB13 - PIN13                        (unused).
 * PB14 - PIN14                        (unused).
 * PB15 - PIN15                        (unused).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_INPUT(GPIOB_PIN0) | \
                                        PIN_MODE_OUTPUT(GPIOB_CS2) | \
                                        PIN_MODE_INPUT(GPIOB_PIN2) | \
                                        PIN_MODE_OUTPUT(GPIOB_CS3) | \
                                        PIN_MODE_INPUT(GPIOB_PIN4) | \
                                        PIN_MODE_INPUT(GPIOB_PIN5) | \
                                        PIN_MODE_OUTPUT(GPIOB_LED_RED) | \
                                        PIN_MODE_INPUT(GPIOB_PIN7) | \
                                        PIN_MODE_INPUT(GPIOB_PIN8) | \
                                        PIN_MODE_INPUT(GPIOB_PIN9) | \
                                        PIN_MODE_INPUT(GPIOB_PIN10) | \
                                        PIN_MODE_INPUT(GPIOB_PIN11) | \
                                        PIN_MODE_INPUT(GPIOB_PIN12) | \
                                        PIN_MODE_INPUT(GPIOB_PIN13) | \
                                        PIN_MODE_INPUT(GPIOB_PIN14) | \
                                        PIN_MODE_INPUT(GPIOB_PIN15))
#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CS2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CS3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_LED_RED) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN15))
#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOB_CS2) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOB_CS3) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOB_LED_RED) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN15))
#define VAL_GPIOB_PUPDR                (PIN_PUPD_PULLUP(GPIOB_PIN0) | \
                                        PIN_PUPD_FLOATING(GPIOB_CS2) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN2) | \
                                        PIN_PUPD_FLOATING(GPIOB_CS3) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN5) | \
                                        PIN_PUPD_FLOATING(GPIOB_LED_RED) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN15))
#define VAL_GPIOB_ODR                  (PIN_OD_HIGH(GPIOB_PIN0) | \
                                        PIN_OD_HIGH(GPIOB_CS2) | \
                                        PIN_OD_HIGH(GPIOB_PIN2) | \
                                        PIN_OD_HIGH(GPIOB_CS3) | \
                                        PIN_OD_HIGH(GPIOB_PIN4) | \
                                        PIN_OD_HIGH(GPIOB_PIN5) | \
                                        PIN_OD_LOW(GPIOB_LED_RED) | \
                                        PIN_OD_HIGH(GPIOB_PIN7) | \
                                        PIN_OD_HIGH(GPIOB_PIN8) | \
                                        PIN_OD_HIGH(GPIOB_PIN9) | \
                                        PIN_OD_HIGH(GPIOB_PIN10) | \
                                        PIN_OD_HIGH(GPIOB_PIN11) | \
                                        PIN_OD_HIGH(GPIOB_PIN12) | \
                                        PIN_OD_HIGH(GPIOB_PIN13) | \
                                        PIN_OD_HIGH(GPIOB_PIN14) | \
                                        PIN_OD_HIGH(GPIOB_PIN15))
#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CS2, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CS3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOB_LED_RED, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN7, 0U))
#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN15, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - PIN0                         (unused).
 * PC1  - PIN1                         (unused).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - PIN4                         (unused).
 * PC5  - PIN5                         (unused).
 * PC6  - PIN6                         (unused).
 * PC7  - PIN7                         (unused).
 * PC8  - PIN8                         (unused).
 * PC9  - PIN9                         (unused).
 * PC10 - PIN10                        (unused).
 * PC11 - PIN11                        (unused).
 * PC12 - PIN12                        (unused).
 * PC13 - PIN13                        (unused).
 * PC14 - PIN14                        (unused).
 * PC15 - PIN15                        (unused).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_INPUT(GPIOC_PIN0) | \
                                        PIN_MODE_INPUT(GPIOC_PIN1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_INPUT(GPIOC_PIN4) | \
                                        PIN_MODE_INPUT(GPIOC_PIN5) | \
                                        PIN_MODE_INPUT(GPIOC_PIN6) | \
                                        PIN_MODE_INPUT(GPIOC_PIN7) | \
                                        PIN_MODE_INPUT(GPIOC_PIN8) | \
                                        PIN_MODE_INPUT(GPIOC_PIN9) | \
                                        PIN_MODE_INPUT(GPIOC_PIN10) | \
                                        PIN_MODE_INPUT(GPIOC_PIN11) | \
                                        PIN_MODE_INPUT(GPIOC_PIN12) | \
                                        PIN_MODE_INPUT(GPIOC_PIN13) | \
                                        PIN_MODE_INPUT(GPIOC_PIN14) | \
                                        PIN_MODE_INPUT(GPIOC_PIN15))
#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN15))
#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN15))
#define VAL_GPIOC_PUPDR                (PIN_PUPD_PULLUP(GPIOC_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN15))
#define VAL_GPIOC_ODR                  (PIN_OD_HIGH(GPIOC_PIN0) | \
                                        PIN_OD_HIGH(GPIOC_PIN1) | \
                                        PIN_OD_HIGH(GPIOC_PIN2) | \
                                        PIN_OD_HIGH(GPIOC_PIN3) | \
                                        PIN_OD_HIGH(GPIOC_PIN4) | \
                                        PIN_OD_HIGH(GPIOC_PIN5) | \
                                        PIN_OD_HIGH(GPIOC_PIN6) | \
                                        PIN_OD_HIGH(GPIOC_PIN7) | \
                                        PIN_OD_HIGH(GPIOC_PIN8) | \
                                        PIN_OD_HIGH(GPIOC_PIN9) | \
                                        PIN_OD_HIGH(GPIOC_PIN10) | \
                                        PIN_OD_HIGH(GPIOC_PIN11) | \
                                        PIN_OD_HIGH(GPIOC_PIN12) | \
                                        PIN_OD_HIGH(GPIOC_PIN13) | \
                                        PIN_OD_HIGH(GPIOC_PIN14) | \
                                        PIN_OD_HIGH(GPIOC_PIN15))
#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN7, 0U))
#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN15, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))
#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))
#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLUP(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN15))
#define VAL_GPIOD_ODR                  (PIN_OD_HIGH(GPIOD_PIN0) | \
                                        PIN_OD_HIGH(GPIOD_PIN1) | \
                                        PIN_OD_HIGH(GPIOD_PIN2) | \
                                        PIN_OD_HIGH(GPIOD_PIN3) | \
                                        PIN_OD_HIGH(GPIOD_PIN4) | \
                                        PIN_OD_HIGH(GPIOD_PIN5) | \
                                        PIN_OD_HIGH(GPIOD_PIN6) | \
                                        PIN_OD_HIGH(GPIOD_PIN7) | \
                                        PIN_OD_HIGH(GPIOD_PIN8) | \
                                        PIN_OD_HIGH(GPIOD_PIN9) | \
                                        PIN_OD_HIGH(GPIOD_PIN10) | \
                                        PIN_OD_HIGH(GPIOD_PIN11) | \
                                        PIN_OD_HIGH(GPIOD_PIN12) | \
                                        PIN_OD_HIGH(GPIOD_PIN13) | \
                                        PIN_OD_HIGH(GPIOD_PIN14) | \
                                        PIN_OD_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))
#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOF setup:
 *
 * PF0  - PIN0                         (unused).
 * PF1  - PIN1                         (unused).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - PIN6                         (unused).
 * PF7  - PIN7                         (unused).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_INPUT(GPIOF_PIN0) | \
                                        PIN_MODE_INPUT(GPIOF_PIN1) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_PIN6) | \
                                        PIN_MODE_INPUT(GPIOF_PIN7) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))
#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))
#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_PUPDR                (PIN_PUPD_PULLUP(GPIOF_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN15))
#define VAL_GPIOF_ODR                  (PIN_OD_HIGH(GPIOF_PIN0) | \
                                        PIN_OD_HIGH(GPIOF_PIN1) | \
                                        PIN_OD_HIGH(GPIOF_PIN2) | \
                                        PIN_OD_HIGH(GPIOF_PIN3) | \
                                        PIN_OD_HIGH(GPIOF_PIN4) | \
                                        PIN_OD_HIGH(GPIOF_PIN5) | \
                                        PIN_OD_HIGH(GPIOF_PIN6) | \
                                        PIN_OD_HIGH(GPIOF_PIN7) | \
                                        PIN_OD_HIGH(GPIOF_PIN8) | \
                                        PIN_OD_HIGH(GPIOF_PIN9) | \
                                        PIN_OD_HIGH(GPIOF_PIN10) | \
                                        PIN_OD_HIGH(GPIOF_PIN11) | \
                                        PIN_OD_HIGH(GPIOF_PIN12) | \
                                        PIN_OD_HIGH(GPIOF_PIN13) | \
                                        PIN_OD_HIGH(GPIOF_PIN14) | \
                                        PIN_OD_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN7, 0U))
#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
