# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/toad_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_toad_main_window(object):
    def setupUi(self, toad_main_window):
        toad_main_window.setObjectName(_fromUtf8("toad_main_window"))
        toad_main_window.resize(1048, 747)
        self.centralwidget = QtGui.QWidget(toad_main_window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.main_tab = QtGui.QWidget()
        self.main_tab.setObjectName(_fromUtf8("main_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.main_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.main_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 977, 658))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_dart_location = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_dart_location.setMinimumSize(QtCore.QSize(290, 0))
        self.frame_dart_location.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.frame_dart_location.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_dart_location.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_dart_location.setObjectName(_fromUtf8("frame_dart_location"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_dart_location)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_dart_position = QtGui.QLabel(self.frame_dart_location)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_dart_position.setFont(font)
        self.label_dart_position.setObjectName(_fromUtf8("label_dart_position"))
        self.verticalLayout_3.addWidget(self.label_dart_position)
        self.formWidget_2 = QtGui.QWidget(self.frame_dart_location)
        self.formWidget_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.formWidget_2.setObjectName(_fromUtf8("formWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.formWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.m_unit_label_2 = QtGui.QLabel(self.formWidget_2)
        self.m_unit_label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.m_unit_label_2.setObjectName(_fromUtf8("m_unit_label_2"))
        self.gridLayout_2.addWidget(self.m_unit_label_2, 1, 2, 1, 1)
        self.max_alt_label = QtGui.QLabel(self.formWidget_2)
        self.max_alt_label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.max_alt_label.setFont(font)
        self.max_alt_label.setObjectName(_fromUtf8("max_alt_label"))
        self.gridLayout_2.addWidget(self.max_alt_label, 1, 0, 1, 1)
        self.altitude_label = QtGui.QLabel(self.formWidget_2)
        self.altitude_label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.altitude_label.setFont(font)
        self.altitude_label.setObjectName(_fromUtf8("altitude_label"))
        self.gridLayout_2.addWidget(self.altitude_label, 0, 0, 1, 1)
        self.m_unit_label = QtGui.QLabel(self.formWidget_2)
        self.m_unit_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.m_unit_label.setObjectName(_fromUtf8("m_unit_label"))
        self.gridLayout_2.addWidget(self.m_unit_label, 0, 2, 1, 1)
        self.altimeter = QtGui.QLCDNumber(self.formWidget_2)
        self.altimeter.setMaximumSize(QtCore.QSize(550, 16777215))
        self.altimeter.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.altimeter.setObjectName(_fromUtf8("altimeter"))
        self.gridLayout_2.addWidget(self.altimeter, 0, 1, 1, 1)
        self.speed_label = QtGui.QLabel(self.formWidget_2)
        self.speed_label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.speed_label.setFont(font)
        self.speed_label.setObjectName(_fromUtf8("speed_label"))
        self.gridLayout_2.addWidget(self.speed_label, 2, 0, 1, 1)
        self.m_s_unit_label = QtGui.QLabel(self.formWidget_2)
        self.m_s_unit_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.m_s_unit_label.setObjectName(_fromUtf8("m_s_unit_label"))
        self.gridLayout_2.addWidget(self.m_s_unit_label, 2, 2, 1, 1)
        self.max_alt_value = QtGui.QLCDNumber(self.formWidget_2)
        self.max_alt_value.setMaximumSize(QtCore.QSize(550, 16777215))
        self.max_alt_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.max_alt_value.setObjectName(_fromUtf8("max_alt_value"))
        self.gridLayout_2.addWidget(self.max_alt_value, 1, 1, 1, 1)
        self.pushButton_zero = QtGui.QPushButton(self.formWidget_2)
        self.pushButton_zero.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_zero.setStyleSheet(_fromUtf8("background-color: rgb(203, 203, 203);"))
        self.pushButton_zero.setObjectName(_fromUtf8("pushButton_zero"))
        self.gridLayout_2.addWidget(self.pushButton_zero, 3, 1, 1, 1)
        self.lineEdit_speed = QtGui.QLineEdit(self.formWidget_2)
        self.lineEdit_speed.setMaximumSize(QtCore.QSize(550, 16777215))
        self.lineEdit_speed.setReadOnly(True)
        self.lineEdit_speed.setObjectName(_fromUtf8("lineEdit_speed"))
        self.gridLayout_2.addWidget(self.lineEdit_speed, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.formWidget_2)
        self.scrollArea_2 = QtGui.QScrollArea(self.frame_dart_location)
        self.scrollArea_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 889, 432))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.latitudeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.latitudeLabel.setObjectName(_fromUtf8("latitudeLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.latitudeLabel)
        self.latitudeLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.latitudeLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.latitudeLineEdit.setReadOnly(True)
        self.latitudeLineEdit.setObjectName(_fromUtf8("latitudeLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.latitudeLineEdit)
        self.longitudeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.longitudeLabel.setObjectName(_fromUtf8("longitudeLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.longitudeLabel)
        self.longitudeLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.longitudeLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.longitudeLineEdit.setReadOnly(True)
        self.longitudeLineEdit.setObjectName(_fromUtf8("longitudeLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.longitudeLineEdit)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setMaximumSize(QtCore.QSize(500, 16777215))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.line)
        self.displacementLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.displacementLabel.setFont(font)
        self.displacementLabel.setObjectName(_fromUtf8("displacementLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.displacementLabel)
        self.dxLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.dxLabel.setObjectName(_fromUtf8("dxLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.dxLabel)
        self.dxLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.dxLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dxLineEdit.setReadOnly(True)
        self.dxLineEdit.setObjectName(_fromUtf8("dxLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dxLineEdit)
        self.dyLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.dyLabel.setObjectName(_fromUtf8("dyLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.dyLabel)
        self.dyLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.dyLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dyLineEdit.setReadOnly(True)
        self.dyLineEdit.setObjectName(_fromUtf8("dyLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.dyLineEdit)
        self.dzLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.dzLabel.setObjectName(_fromUtf8("dzLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.dzLabel)
        self.dzLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.dzLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dzLineEdit.setReadOnly(True)
        self.dzLineEdit.setObjectName(_fromUtf8("dzLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.dzLineEdit)
        self.dxDtLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.dxDtLabel.setObjectName(_fromUtf8("dxDtLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.dxDtLabel)
        self.dxdtLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.dxdtLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dxdtLineEdit.setReadOnly(True)
        self.dxdtLineEdit.setObjectName(_fromUtf8("dxdtLineEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.dxdtLineEdit)
        self.dyDtLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.dyDtLabel.setObjectName(_fromUtf8("dyDtLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.dyDtLabel)
        self.dydtLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.dydtLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dydtLineEdit.setReadOnly(True)
        self.dydtLineEdit.setObjectName(_fromUtf8("dydtLineEdit"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.dydtLineEdit)
        self.dzDtLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.dzDtLabel.setObjectName(_fromUtf8("dzDtLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.dzDtLabel)
        self.dzdtLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.dzdtLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dzdtLineEdit.setReadOnly(True)
        self.dzdtLineEdit.setObjectName(_fromUtf8("dzdtLineEdit"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.dzdtLineEdit)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.label)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.gridLayout.addWidget(self.frame_dart_location, 0, 4, 1, 1)
        self.frame_toad_1 = toad_frame_1(self.scrollAreaWidgetContents)
        self.frame_toad_1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame_toad_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_1.setObjectName(_fromUtf8("frame_toad_1"))
        self.gridLayout.addWidget(self.frame_toad_1, 0, 1, 1, 1)
        self.frame_toad_2 = toad_frame_2(self.scrollAreaWidgetContents)
        self.frame_toad_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame_toad_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_2.setObjectName(_fromUtf8("frame_toad_2"))
        self.gridLayout.addWidget(self.frame_toad_2, 0, 2, 1, 1)
        self.frame_toad_3 = toad_frame_3(self.scrollAreaWidgetContents)
        self.frame_toad_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame_toad_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_3.setObjectName(_fromUtf8("frame_toad_3"))
        self.gridLayout.addWidget(self.frame_toad_3, 0, 3, 1, 1)
        self.frame_toad_4 = toad_frame_4(self.scrollAreaWidgetContents)
        self.frame_toad_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame_toad_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_4.setObjectName(_fromUtf8("frame_toad_4"))
        self.gridLayout.addWidget(self.frame_toad_4, 1, 1, 1, 1)
        self.frame_toad_5 = toad_frame_5(self.scrollAreaWidgetContents)
        self.frame_toad_5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame_toad_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_5.setObjectName(_fromUtf8("frame_toad_5"))
        self.gridLayout.addWidget(self.frame_toad_5, 1, 2, 1, 1)
        self.frame_toad_6 = toad_frame_6(self.scrollAreaWidgetContents)
        self.frame_toad_6.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame_toad_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_6.setObjectName(_fromUtf8("frame_toad_6"))
        self.gridLayout.addWidget(self.frame_toad_6, 1, 3, 1, 1)
        self.frame_toad_master = toad_frame_master(self.scrollAreaWidgetContents)
        self.frame_toad_master.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_toad_master.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_toad_master.setObjectName(_fromUtf8("frame_toad_master"))
        self.gridLayout.addWidget(self.frame_toad_master, 1, 4, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.main_tab, _fromUtf8(""))
        self.term_tab = QtGui.QWidget()
        self.term_tab.setObjectName(_fromUtf8("term_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.term_tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textBrowser_terminal = QtGui.QTextBrowser(self.term_tab)
        self.textBrowser_terminal.setObjectName(_fromUtf8("textBrowser_terminal"))
        self.verticalLayout_5.addWidget(self.textBrowser_terminal)
        self.tabWidget.addTab(self.term_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        toad_main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(toad_main_window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        toad_main_window.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(toad_main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        toad_main_window.setMenuBar(self.menubar)
        self.actionSave_Terminal = QtGui.QAction(toad_main_window)
        self.actionSave_Terminal.setObjectName(_fromUtf8("actionSave_Terminal"))
        self.menuFile.addAction(self.actionSave_Terminal)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(toad_main_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(toad_main_window)
        toad_main_window.setTabOrder(self.scrollArea, self.frame_toad_1)
        toad_main_window.setTabOrder(self.frame_toad_1, self.frame_toad_2)
        toad_main_window.setTabOrder(self.frame_toad_2, self.frame_toad_3)
        toad_main_window.setTabOrder(self.frame_toad_3, self.frame_toad_4)
        toad_main_window.setTabOrder(self.frame_toad_4, self.frame_toad_5)
        toad_main_window.setTabOrder(self.frame_toad_5, self.frame_toad_6)
        toad_main_window.setTabOrder(self.frame_toad_6, self.scrollArea_2)
        toad_main_window.setTabOrder(self.scrollArea_2, self.latitudeLineEdit)
        toad_main_window.setTabOrder(self.latitudeLineEdit, self.longitudeLineEdit)
        toad_main_window.setTabOrder(self.longitudeLineEdit, self.dxLineEdit)
        toad_main_window.setTabOrder(self.dxLineEdit, self.dyLineEdit)
        toad_main_window.setTabOrder(self.dyLineEdit, self.dzLineEdit)
        toad_main_window.setTabOrder(self.dzLineEdit, self.dxdtLineEdit)
        toad_main_window.setTabOrder(self.dxdtLineEdit, self.dydtLineEdit)
        toad_main_window.setTabOrder(self.dydtLineEdit, self.dzdtLineEdit)

    def retranslateUi(self, toad_main_window):
        toad_main_window.setWindowTitle(_translate("toad_main_window", "TOAD GCS", None))
        self.label_dart_position.setText(_translate("toad_main_window", "Dart Position", None))
        self.m_unit_label_2.setText(_translate("toad_main_window", "m", None))
        self.max_alt_label.setText(_translate("toad_main_window", "Max alt", None))
        self.altitude_label.setText(_translate("toad_main_window", "Altitude", None))
        self.m_unit_label.setText(_translate("toad_main_window", "m", None))
        self.speed_label.setText(_translate("toad_main_window", "Speed", None))
        self.m_s_unit_label.setText(_translate("toad_main_window", "m/s", None))
        self.pushButton_zero.setText(_translate("toad_main_window", "Set as start point", None))
        self.latitudeLabel.setText(_translate("toad_main_window", "Latitude", None))
        self.longitudeLabel.setText(_translate("toad_main_window", "Longitude", None))
        self.displacementLabel.setText(_translate("toad_main_window", "Displacement from pad", None))
        self.dxLabel.setText(_translate("toad_main_window", "Δx (East)", None))
        self.dyLabel.setText(_translate("toad_main_window", "Δy (North)", None))
        self.dzLabel.setText(_translate("toad_main_window", "Δz (Up)", None))
        self.dxDtLabel.setText(_translate("toad_main_window", "dx/dt", None))
        self.dyDtLabel.setText(_translate("toad_main_window", "dy/dt", None))
        self.dzDtLabel.setText(_translate("toad_main_window", "dz/dt", None))
        self.label.setText(_translate("toad_main_window", "Velocity Estimates", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("toad_main_window", "Main", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.term_tab), _translate("toad_main_window", "Terminal", None))
        self.menuFile.setTitle(_translate("toad_main_window", "File", None))
        self.actionSave_Terminal.setText(_translate("toad_main_window", "&Save \'Terminal\'", None))
        self.actionSave_Terminal.setIconText(_translate("toad_main_window", "&Save \'Terminal\'", None))
        self.actionSave_Terminal.setShortcut(_translate("toad_main_window", "Ctrl+S", None))

from .toad_frame_1 import toad_frame_1
from .toad_frame_2 import toad_frame_2
from .toad_frame_3 import toad_frame_3
from .toad_frame_4 import toad_frame_4
from .toad_frame_5 import toad_frame_5
from .toad_frame_6 import toad_frame_6
from .toad_frame_master import toad_frame_master
