# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/toad_frame.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_toad_frame(object):
    def setupUi(self, toad_frame):
        toad_frame.setObjectName(_fromUtf8("toad_frame"))
        toad_frame.resize(276, 600)
        toad_frame.setMinimumSize(QtCore.QSize(276, 600))
        toad_frame.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        toad_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        toad_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(toad_frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_ranging_2 = QtGui.QFormLayout()
        self.formLayout_ranging_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_ranging_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_ranging_2.setObjectName(_fromUtf8("formLayout_ranging_2"))
        self.label_ranging_title_2 = QtGui.QLabel(toad_frame)
        self.label_ranging_title_2.setMaximumSize(QtCore.QSize(640, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_ranging_title_2.setFont(font)
        self.label_ranging_title_2.setObjectName(_fromUtf8("label_ranging_title_2"))
        self.formLayout_ranging_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_ranging_title_2)
        self.label_timestamp_2 = QtGui.QLabel(toad_frame)
        self.label_timestamp_2.setIndent(-1)
        self.label_timestamp_2.setObjectName(_fromUtf8("label_timestamp_2"))
        self.formLayout_ranging_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_timestamp_2)
        self.lineEdit_timestamp_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_timestamp_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_timestamp_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_timestamp_2.setReadOnly(True)
        self.lineEdit_timestamp_2.setObjectName(_fromUtf8("lineEdit_timestamp_2"))
        self.formLayout_ranging_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_timestamp_2)
        self.label_timestamp_itow_2 = QtGui.QLabel(toad_frame)
        self.label_timestamp_itow_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_timestamp_itow_2.setIndent(25)
        self.label_timestamp_itow_2.setObjectName(_fromUtf8("label_timestamp_itow_2"))
        self.formLayout_ranging_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_timestamp_itow_2)
        self.lineEdit_timestamp_itow_3 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_timestamp_itow_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_timestamp_itow_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_timestamp_itow_3.setReadOnly(True)
        self.lineEdit_timestamp_itow_3.setObjectName(_fromUtf8("lineEdit_timestamp_itow_3"))
        self.formLayout_ranging_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_timestamp_itow_3)
        self.label_timestamp_systicks_2 = QtGui.QLabel(toad_frame)
        self.label_timestamp_systicks_2.setIndent(25)
        self.label_timestamp_systicks_2.setObjectName(_fromUtf8("label_timestamp_systicks_2"))
        self.formLayout_ranging_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_timestamp_systicks_2)
        self.lineEdit_timestamp_systicks_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_timestamp_systicks_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_timestamp_systicks_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_timestamp_systicks_2.setReadOnly(True)
        self.lineEdit_timestamp_systicks_2.setObjectName(_fromUtf8("lineEdit_timestamp_systicks_2"))
        self.formLayout_ranging_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_timestamp_systicks_2)
        self.label_tof_2 = QtGui.QLabel(toad_frame)
        self.label_tof_2.setWordWrap(True)
        self.label_tof_2.setIndent(-1)
        self.label_tof_2.setObjectName(_fromUtf8("label_tof_2"))
        self.formLayout_ranging_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_tof_2)
        self.lineEdit_tof_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_tof_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_tof_2.setReadOnly(True)
        self.lineEdit_tof_2.setObjectName(_fromUtf8("lineEdit_tof_2"))
        self.formLayout_ranging_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_tof_2)
        self.label_timerfreq_2 = QtGui.QLabel(toad_frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_timerfreq_2.setFont(font)
        self.label_timerfreq_2.setIndent(25)
        self.label_timerfreq_2.setObjectName(_fromUtf8("label_timerfreq_2"))
        self.formLayout_ranging_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_timerfreq_2)
        self.spinBox_timerfreq_2 = QtGui.QSpinBox(toad_frame)
        self.spinBox_timerfreq_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.spinBox_timerfreq_2.setMaximum(99999999)
        self.spinBox_timerfreq_2.setSingleStep(1000)
        self.spinBox_timerfreq_2.setProperty("value", 84000000)
        self.spinBox_timerfreq_2.setObjectName(_fromUtf8("spinBox_timerfreq_2"))
        self.formLayout_ranging_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.spinBox_timerfreq_2)
        self.label_distance_2 = QtGui.QLabel(toad_frame)
        self.label_distance_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_distance_2.setIndent(25)
        self.label_distance_2.setObjectName(_fromUtf8("label_distance_2"))
        self.formLayout_ranging_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_distance_2)
        self.lineEdit_distance_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_distance_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_distance_2.setReadOnly(True)
        self.lineEdit_distance_2.setObjectName(_fromUtf8("lineEdit_distance_2"))
        self.formLayout_ranging_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_distance_2)
        self.verticalLayout.addLayout(self.formLayout_ranging_2)
        self.line_2 = QtGui.QFrame(toad_frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.formLayout_pos_2 = QtGui.QFormLayout()
        self.formLayout_pos_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_pos_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_pos_2.setObjectName(_fromUtf8("formLayout_pos_2"))
        self.label_pos_2 = QtGui.QLabel(toad_frame)
        self.label_pos_2.setMaximumSize(QtCore.QSize(640, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_pos_2.setFont(font)
        self.label_pos_2.setObjectName(_fromUtf8("label_pos_2"))
        self.formLayout_pos_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_pos_2)
        self.label_pos_timestamp_2 = QtGui.QLabel(toad_frame)
        self.label_pos_timestamp_2.setMinimumSize(QtCore.QSize(136, 0))
        self.label_pos_timestamp_2.setIndent(-1)
        self.label_pos_timestamp_2.setObjectName(_fromUtf8("label_pos_timestamp_2"))
        self.formLayout_pos_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_pos_timestamp_2)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(toad_frame)
        self.dateTimeEdit_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dateTimeEdit_2.setReadOnly(True)
        self.dateTimeEdit_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.formLayout_pos_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateTimeEdit_2)
        self.label_pos_itow_2 = QtGui.QLabel(toad_frame)
        self.label_pos_itow_2.setIndent(25)
        self.label_pos_itow_2.setObjectName(_fromUtf8("label_pos_itow_2"))
        self.formLayout_pos_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_pos_itow_2)
        self.lineEdit_timestamp_itow_4 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_timestamp_itow_4.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_timestamp_itow_4.setReadOnly(True)
        self.lineEdit_timestamp_itow_4.setObjectName(_fromUtf8("lineEdit_timestamp_itow_4"))
        self.formLayout_pos_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_timestamp_itow_4)
        self.label_pos_systicks_2 = QtGui.QLabel(toad_frame)
        self.label_pos_systicks_2.setIndent(25)
        self.label_pos_systicks_2.setObjectName(_fromUtf8("label_pos_systicks_2"))
        self.formLayout_pos_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_pos_systicks_2)
        self.lineEdit_timestamp_st_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_timestamp_st_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_timestamp_st_2.setReadOnly(True)
        self.lineEdit_timestamp_st_2.setObjectName(_fromUtf8("lineEdit_timestamp_st_2"))
        self.formLayout_pos_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_timestamp_st_2)
        self.label_lat_2 = QtGui.QLabel(toad_frame)
        self.label_lat_2.setObjectName(_fromUtf8("label_lat_2"))
        self.formLayout_pos_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_lat_2)
        self.lineEdit_lat_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_lat_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_lat_2.setReadOnly(True)
        self.lineEdit_lat_2.setObjectName(_fromUtf8("lineEdit_lat_2"))
        self.formLayout_pos_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_lat_2)
        self.label_lon_2 = QtGui.QLabel(toad_frame)
        self.label_lon_2.setObjectName(_fromUtf8("label_lon_2"))
        self.formLayout_pos_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_lon_2)
        self.lineEdit_lon_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_lon_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_lon_2.setReadOnly(True)
        self.lineEdit_lon_2.setObjectName(_fromUtf8("lineEdit_lon_2"))
        self.formLayout_pos_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_lon_2)
        self.label_height_2 = QtGui.QLabel(toad_frame)
        self.label_height_2.setObjectName(_fromUtf8("label_height_2"))
        self.formLayout_pos_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_height_2)
        self.lineEdit_height_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_height_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_height_2.setReadOnly(True)
        self.lineEdit_height_2.setObjectName(_fromUtf8("lineEdit_height_2"))
        self.formLayout_pos_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_height_2)
        self.label_numsat_2 = QtGui.QLabel(toad_frame)
        self.label_numsat_2.setObjectName(_fromUtf8("label_numsat_2"))
        self.formLayout_pos_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_numsat_2)
        self.lineEdit_num_sat_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_num_sat_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_num_sat_2.setReadOnly(True)
        self.lineEdit_num_sat_2.setObjectName(_fromUtf8("lineEdit_num_sat_2"))
        self.formLayout_pos_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_num_sat_2)
        self.line_3 = QtGui.QFrame(toad_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.formLayout_pos_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.line_3)
        self.label_batt_v_2 = QtGui.QLabel(toad_frame)
        self.label_batt_v_2.setObjectName(_fromUtf8("label_batt_v_2"))
        self.formLayout_pos_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_batt_v_2)
        self.lineEdit_batt_v_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_batt_v_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_batt_v_2.setReadOnly(True)
        self.lineEdit_batt_v_2.setObjectName(_fromUtf8("lineEdit_batt_v_2"))
        self.formLayout_pos_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_batt_v_2)
        self.label_cpu_temp_2 = QtGui.QLabel(toad_frame)
        self.label_cpu_temp_2.setObjectName(_fromUtf8("label_cpu_temp_2"))
        self.formLayout_pos_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_cpu_temp_2)
        self.lineEdit_cpu_temp_2 = QtGui.QLineEdit(toad_frame)
        self.lineEdit_cpu_temp_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_cpu_temp_2.setReadOnly(True)
        self.lineEdit_cpu_temp_2.setObjectName(_fromUtf8("lineEdit_cpu_temp_2"))
        self.formLayout_pos_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit_cpu_temp_2)
        self.verticalLayout.addLayout(self.formLayout_pos_2)

        self.retranslateUi(toad_frame)
        QtCore.QMetaObject.connectSlotsByName(toad_frame)

    def retranslateUi(self, toad_frame):
        toad_frame.setWindowTitle(_translate("toad_frame", "toad_frame", None))
        self.label_ranging_title_2.setText(_translate("toad_frame", "Ranging", None))
        self.label_timestamp_2.setText(_translate("toad_frame", "Timestamp", None))
        self.label_timestamp_itow_2.setText(_translate("toad_frame", "(ITOW)", None))
        self.label_timestamp_systicks_2.setText(_translate("toad_frame", "(systicks)", None))
        self.label_tof_2.setText(_translate("toad_frame", "Time of flight (timer register)", None))
        self.label_timerfreq_2.setText(_translate("toad_frame", "Enter timer freq:", None))
        self.spinBox_timerfreq_2.setSuffix(_translate("toad_frame", "Hz", None))
        self.label_distance_2.setText(_translate("toad_frame", "Distance/m", None))
        self.label_pos_2.setText(_translate("toad_frame", "Position and Health", None))
        self.label_pos_timestamp_2.setText(_translate("toad_frame", "Timestamp", None))
        self.label_pos_itow_2.setText(_translate("toad_frame", "(ITOW)", None))
        self.label_pos_systicks_2.setText(_translate("toad_frame", "(systicks)", None))
        self.label_lat_2.setText(_translate("toad_frame", "Latitude", None))
        self.label_lon_2.setText(_translate("toad_frame", "Longitude", None))
        self.label_height_2.setText(_translate("toad_frame", "Height", None))
        self.label_numsat_2.setText(_translate("toad_frame", "No. of sats", None))
        self.label_batt_v_2.setText(_translate("toad_frame", "Battery voltage", None))
        self.label_cpu_temp_2.setText(_translate("toad_frame", "CPU temperature", None))


class toad_frame(QtGui.QFrame, Ui_toad_frame):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QFrame.__init__(self, parent, f)

        self.setupUi(self)

